<div class="text">
<p>The following is from Blizzard, <a href="http://us.battle.net/wow/en/forum/topic/3196342583" target="_blank">source here</a></p>

<ul>
<li>The character must be able to equip both items.</li>
<li>Only <span class="q2">uncommon</span>, <span class="q3">rare</span> or <span class="q4">epic</span> items may be transmogrified. (exceptions: a select few of these items will be prevented from being used to transmogrify if they are inappropriate)</li>
<li>Items must share the same armor type (examples: plate for plate, cloth for cloth)</li>
<li>Weapons must be the same weapon type (exceptions: Guns, Crossbows, or Bows)</li>
<li>Guns, Crossbows, and Bows can be used to transmogrify Guns, Crossbows, or Bows.</li>
<li>Main hand weapons can only be used to transmogrify Main hand weapons.</li>
<li>Off-hand weapons can only be used to transmogrify Off-hand weapons.</li>
<li>One handed weapons can be used to transmogrify a Main hand or Off-hand weapon.</li>
<li>Using an item for transmogrify makes it soulbound.</li>
<li>Using an item for transmogrify makes it non-refundable.</li>
<li>Using an item for transmogrify makes it non-tradable.</li>
<li><span class="q7">Heirlooms</span> and Account Bound items can be transmogrified.</li>
<li><span class="q7">Heirlooms</span> and Account Bound items can be used to transmogrify.</li>
<li><span class="q5">Legendary</span> items cannot be transmogrified.</li>
<li><span class="q5">Legendary</span> items cannot be used to transmogrify.</li>
<li>Fishing Poles cannot be transmogrified.</li>
<li>Fishing Poles cannot be used to transmogrify.</li>
<li>Mailing an item strips its transmogrification.</li>
<li>Placing an item in Void Storage strips its transmogrification.</li>
<li>Vendoring an item strips its transmogrification.</li>
<li>The displayed enchant will be that of the currently equipped item.</li>
<li>There may be individual items that are excluded from being transmogrified on the basis that they were originally added to the game as absurdities. (examples: a weapon that looks like a fish, or a chest piece that is invisible)</li>
</ul>

</div>