<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="content-type" content="text/html;charset=UTF-8">
		<title>Transmogger Screengrabber</title>
		<meta name="description" content="Tranmogrification utility using WoWhead 3D model viewer" />
		<meta name="keywords" content="transmogrification, transmogrify, transmogger, wow, armour, preview" />

		<style>
			body {
				background: #181818 url(/images/bg_screengrab.png) top left repeat;
			}
		</style>
	</head>

	<body>
		<?php echo $this->layout()->content ?>
	</body>
</html>